# -*- coding: utf-8 -*-
""".Lambda Function for Sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm2zZdeQb4Rypm5v0shjB7enO4R2oVVQ
"""

list_of_tuples = [(1, 7), (9, 2), (6, 1), (8, 5)]

sorted_list = sorted(list_of_tuples, key=lambda x: x[1])

print(sorted_list)