# -*- coding: utf-8 -*-
"""Args in Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQvflfKM5-bukw100YHeyQAR-7l17_Ld
"""

def sum_of_numbers(*args):
    return sum(args)

print(sum_of_numbers(1, 2, 3))
print(sum_of_numbers(70, 50, 90, 20))
print(sum_of_numbers(6))
print(sum_of_numbers())