# -*- coding: utf-8 -*-
"""Argument Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e9O8vtMyKjMahcrToG6MAeB6udq-d-uz
"""

def greet(name, message="Hello"):
    return f"{message}, {name}!"

print(greet("Adhit"))
print(greet("Adhit", "Goodbye"))