# -*- coding: utf-8 -*-
"""Armstrong Number Checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2iFj5a2cMgfnOOzat74-v78qkvHy8Df
"""

def is_armstrong(number):
    # Convert the number to a string to easily access each digit
    num_str = str(number)
    num_digits = len(num_str)

    # Calculate the sum of each digit raised to the power of the number of digits
    total = sum(int(digit) ** num_digits for digit in num_str)

    # Check if the total equals the original number
    return total == number

print(is_armstrong(153))  # This will output: True (153 is an Armstrong number)
print(is_armstrong(9474)) # This will output: True (9474 is an Armstrong number)
print(is_armstrong(123))  # This will output: False (123 is not an Armstrong number)