# -*- coding: utf-8 -*-
"""Counting Vowles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uovB3vaBIakkrC6E3DZF381t17GoiOt
"""

def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count

print(count_vowels("Hello World"))  # This will output: 3
print(count_vowels("ADHIT"))      # This will output: 1
print(count_vowels("AEIOU"))       # This will output: 5