# -*- coding: utf-8 -*-
"""fibonacci series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzVZNil21oZbmuxbLry01EsNyTvQ5KFi
"""

def generate_fibonacci(N):
    fibonacci_sequence = []
    a, b = 0, 1
    for _ in range(N):
        fibonacci_sequence.append(a)
        a, b = b, a + b
    return fibonacci_sequence