# -*- coding: utf-8 -*-
"""GCD Using Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tShqk4Xy2LI--vkPyPyjo0ATwYJlPFHF
"""

import math

def gcd(a, b):
    return math.gcd(a, b)

print(gcd(5, 9))
print(gcd(17, 45))
print(gcd(77, 33))