# -*- coding: utf-8 -*-
"""hello python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvNwDV25_QgBgSQc6qVtTcHyoutlhO0K
"""

def greet():
    print("Hello, Python!")

# Call the function
greet()