# -*- coding: utf-8 -*-
"""kwargs in Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XExEfdbFAlMDAorQcghEzvv73jCZeixx
"""

def print_keyword_args(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_keyword_args(Name="ADHIT", Age=19, City="BANGALORE")


print_keyword_args(Language="Python")