# -*- coding: utf-8 -*-
"""Lambda Function for Squaring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfPtyAPi1e63dGoBO1vaQhQudwGoogbx
"""

square = lambda x: x ** 2

print(square(16))