# -*- coding: utf-8 -*-
"""Largest of Three Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isdjv1NzJEFv5eyqP2dl1DUBQhymeVx_
"""

def largest_of_three(num1, num2, num3):
    return max(num1, num2, num3)

print(largest_of_three(5, 100, 3))
print(largest_of_three(20, 150, 25))
print(largest_of_three(79, 17, 77))