# -*- coding: utf-8 -*-
"""Math Moduleipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7rHNhMQPRIfh8FCwjXUmPD6HCaIxnxA
"""

import math

def math_operations(num):

    square_root = math.sqrt(num)


    if num.is_integer() and num >= 0:
        factorial = math.factorial(int(num))
    else:
        factorial = "Factorial is only defined for non-negative integers"


    sine_value = math.sin(math.radians(num))

    return square_root, factorial, sine_value

number = float(input("Enter a number: "))

sqrt, fact, sine = math_operations(number)

print(f"Square root of {number}: {sqrt}")
print(f"Factorial of {number}: {fact}")
print(f"Sine of {number} (in radians): {sine}")