# -*- coding: utf-8 -*-
"""Odd or Even function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fC8u_1IyLUv5KuNyIFmGntQl6gJE-Ohx
"""

def check_even_odd(n):
    if n % 2 == 0:
        return "Even"
    else:
        return "Odd"

print(check_even_odd(4))  # This will output: Even
print(check_even_odd(4))  # This will output: Odd
print(check_even_odd(0))  # This will output: Even