# -*- coding: utf-8 -*-
"""Palindrome Checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAnKIr6ffI3pxJEt7_osa9GbErho4Qp8
"""

def is_palindrome(s):
    # Remove spaces and convert to lowercase for case-insensitive comparison
    s = s.replace(" ", "").lower()

    # Check if the string is equal to its reverse
    return s == s[::-1]

print(is_palindrome("MADAM"))
print(is_palindrome("CASHIER"))
print(is_palindrome("carrcaer"))
print(is_palindrome("DUCK ATE THE FISH IN THE LAKE"))