# -*- coding: utf-8 -*-
"""Power Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T267u89Pt3165KGUZRrqi2XwMowUOVti
"""

def power(base, exponent):
    # Base case: if exponent is 0, return 1 (any number raised to the power of 0 is 1)
    if exponent == 0:
        return 1
    # If the exponent is positive, recursively multiply the base
    elif exponent > 0:
        return base * power(base, exponent - 1)
    # If the exponent is negative, handle by taking the reciprocal
    else:
        return 1 / power(base, -exponent)