# -*- coding: utf-8 -*-
"""Random Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wODvtgPvSehhvNOxmTZnRIkq9UVDbye
"""

import random

def generate_random_number(start, end):
    return random.randint(start, end)

random_number = generate_random_number(10, 100)
print(f"Random number between 1 and 100: {random_number}")

random_number = generate_random_number(40, 80)
print(f"Random number between 50 and 60: {random_number}")