# -*- coding: utf-8 -*-
"""Reversing a String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDnDD8jcL324hVXrmCZNnKfFajj2IuCq
"""

def reverse_string(s):
    return s[::-1]

print(reverse_string("OLLEH"))  # This will output: "olleH"
print(reverse_string("TIHDA")) # This will output: "TIHDA"