# -*- coding: utf-8 -*-
"""sine and cosine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jNmqpH7nfkLQ7vNPxq5Xy0JJHIrTucr
"""

import math
angle=float(input("Enter an angle in degrees: "))
radian=math.radians(angle)
print("Sine:",math.sin(radian))
print("Cosine:",math.cos(radian))