# -*- coding: utf-8 -*-
"""the number is prime or not.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-vP2CvAVLWCyXWhXgruh7Vu6BFUjdO8
"""

def is_prime(n):
    if n <= 1:
        return False  # Numbers less than or equal to 1 are not prime
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:  # If n is divisible by any number between 2 and sqrt(n), it's not prime
            return False
    return True  # If no divisors are found, n is prime