# -*- coding: utf-8 -*-
"""the given number is prime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzVZNil21oZbmuxbLry01EsNyTvQ5KFi
"""

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True